### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by koushikpalnu** [ihalage/Finder#2]
Hi, 

I installed `Finder` in a `conda` environment utilizing the `requirement.txt` file with `python=3.8`. However, when I run `python trainer.py --help`, I get the following error. 

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
Traceback (most recent call last):
  File "trainer.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/home/koushik/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 205, in <module>
    _check_versions()
  File "/home/koushik/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 190, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import

I figured out that this might arise from the lower version of `numpy=1.19.5`.  So I upgraded it to `numpy=1.23.0` and `python trainer.py --help` prints out the usage and arguments without any error. However, this time, when I run the model with `python trainer.py --train-path data/databases/MP_2021_July_no_polymorph/formation_energy/train.csv --val-path data/databases/MP_2021_July_no_polymorph/formation_energy/val.csv --test-path data/databases/MP_2021_July_no_polymorph/formation_energy/test.csv --epochs 800 --batch-size 128 --train --test`, I get the following errors.

Traceback (most recent call last):
  File "trainer.py", line 470, in <module>
    worker.train_model()
  File "trainer.py", line 188, in train_model
    l, tmae = train_step(*batch)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in user code:

    trainer.py:167 train_step  *
        predictions = model(inputs, training=True)
    /projects/p30436/codes/Finder-main/Finder/model.py:237 call  *
        x1 = self.conv1([x, a, e])
    /home/koushik/.local/lib/python3.8/site-packages/spektral/layers/convolutional/message_passing.py:106 call  *
        return self.propagate(x, a, e)
    /home/koushik/.local/lib/python3.8/site-packages/spektral/layers/convolutional/message_passing.py:118 propagate  *
        messages = self.message(x, **msg_kwargs)
    /projects/p30436/codes/Finder-main/Finder/model.py:170 message  *
        global_attr = scatter_mean(neighbors_mean, self.index_i, self.n_nodes)
    /home/koushik/.local/lib/python3.8/site-packages/spektral/layers/ops/scatter.py:8 _wrapper_mm_support  *
        out = scatter_fn(updates, indices, N)
    /home/koushik/.local/lib/python3.8/site-packages/spektral/layers/ops/scatter.py:76 scatter_mean  *
        return tf.math.unsorted_segment_mean(messages, indices, n_nodes)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py:4095 unsorted_segment_mean
        N = _unsorted_segment_N(data, segment_ids, num_segments)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py:4046 _unsorted_segment_N
        array_ops.ones([array_ops.rank(data)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:3120 ones
        output = _constant_if_small(one, shape, dtype, name)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:2804 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:180 prod

    /home/koushik/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3045 prod
        return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
    /home/koushik/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /home/koushik/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:852 __array__
        raise NotImplementedError(

    NotImplementedError: Cannot convert a symbolic Tensor (finder/graph_layer/UnsortedSegmentMean/sub:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Any suggestions how I can get rid of the errors?

Thanks,
Koushik

**Comment by ihalage** [comment]
Hi,

Apologies for the delayed response. I have now updated the repository to use the latest versions of the dependencies. Please clone and install the package again.
